apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    storage: pv-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany #nfs
  volumeMode: Filesystem 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    server: 192.168.138.100
    path: /k8s_share