apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 10Gi     # PV's storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual   
  persistentVolumeReclaimPolicy: Retain # 유지
  hostPath:
    path: /tmp/k8s-pv
