apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: wordpress #빠트린 부분
spec:
  selector:
    matchLabels:
      storage: pv-nfs
  accessModes:
  - ReadWriteMany #nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi