apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport-service
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress-deployment-app
  ports:
  - port: 80 #클러스터 내부 포트 
    protocol: TCP
    targetPort: 80 #클러스터 내부 포트
    nodePort: 30080 #클러스터 외부 포트
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment-app
  namespace: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress-deployment-app
  template:
    metadata:
      labels:
        app: wordpress-deployment-app
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4
        envFrom: # 빠트린 부분, configmap에 설정한 변수 정의한 부분 추가
        - configMapRef: # 빠트린 부분
            name: configmap-wp # 빠트린 부분
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-nfs
          mountPath: /var/www/html
      volumes:
      - name: wordpress-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-autoscaler
  namespace: wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50